bot:
    token: 1800442824:AAHeOsnFDwFGiksD5ZWAx41Xct7zbsXeFsY
    parse_mode: html

executor:
    skip_updates: true

modules:
    - handlers.main
    - handlers.errors

log_ignore:
    - aiogram
    - asyncio
    - aiogram.Middleware

commands:
    start: Начать беседу со мной
